import { defineConfig } from 'oxfmt';

export default defineConfig({
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: 'auto',
  endOfLine: 'lf',
  experimentalOperatorPosition: 'start',
  htmlWhitespaceSensitivity: 'css',
  ignorePatterns: ['dist', 'node_modules', 'routeTree.gen.ts'],
  insertFinalNewline: true,
  jsdoc: false,
  jsxSingleQuote: false,
  objectWrap: 'preserve',
  overrides: [
    {
      files: ['*.tsx'],
      options: {
        jsxSingleQuote: false,
        sortTailwindcss: {
          attributes: ['classNames'],
          functions: ['clsx', 'cn', 'cva', 'tw'],
          preserveDuplicates: false,
          preserveWhitespace: false,
        },
      },
    },
  ],
  printWidth: 100,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  semi: true,
  singleAttributePerLine: false,
  singleQuote: true,
  sortImports: {
    // https://oxc.rs/docs/guide/usage/formatter/config-file-reference.html#sortimports-groups
    groups: [
      'builtin',
      // { newlinesBetween: true },
      'external',
      // { newlinesBetween: true },
      'internal',
      // { newlinesBetween: true },
      ['parent', 'sibling'],
      // { newlinesBetween: true },
      'index',
      // { newlinesBetween: true },
      'type',
    ],
    ignoreCase: true,
    internalPattern: ['#/'],
    order: 'asc',
    newlinesBetween: true,
    partitionByComment: false,
    partitionByNewline: false,
    sortSideEffects: false,
  },
  sortPackageJson: true,
  sortTailwindcss: {
    attributes: ['classNames'],
    functions: ['cn', 'clsx', 'cva', 'tw'],
    preserveDuplicates: false,
    preserveWhitespace: false,
  },
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
});
