packages:
  - "packages/*"
  - "apps/*"
minimumReleaseAgeStrict: true
allowBuilds:
  "@prisma/engines": true
  esbuild: true
  lightningcss: true
  prisma: false
minimumReleaseAgeExclude:
  - "@clerk/backend"
  - "@clerk/react"
  - "@clerk/shared"
  - "@clerk/tanstack-react-start"
  - "@types/node"
